# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: .

jobs:
  # Please do not rename this job
  build-project:
    name: build telegram_bot2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: pip install -r bot/requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          VIC_PORT: 465
          ANGEL_PORT: 587
          VIVA_PORT: 465
          VIC_PASSWORD: ${{ secrets.VIC_PASSWORD }}
          ANGEL_PASSWORD: ${{ secrets.ANGEL_PASSWORD }}
          VIVA_PASSWORD: ${{ secrets.VIVA_PASSWORD }}
        run: python3 bot/main.py

      # Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: b2055d54-6013-422c-9740-7e96af8d601f
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/telegram_bot2/config.yaml
          action: upload
